---
- include: setup-AWS.yml
  when: "ansible_distribution == 'Amazon'"

- include: setup-Ubuntu.yml
  when: "ansible_distribution == 'Ubuntu'"


- name: Install docker library for python to control docker from ansible
  pip: name=docker

- name: Install docker-compose
  pip: name=docker-compose